### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by norcalli** [myitcv/neogo#2]
```
./neogo.go:37: assignment count mismatch: 2 = 1
./neogo.go:46: cb.GetSlice undefined (type neovim.Buffer has no field or method GetSlice)
```

I would like to start playing with this, but it seems outdated now. I am considering reading all of the neovim package source that you wrote, but I would hope you could fix this faster than I could.

**Comment by myitcv** [comment]
@norcalli - apologies. No idea how I missed your message. Yes this is outdated... but also I fell somewhat off the radar of maintaining https://github.com/myitcv/neovim

I've just merged [an important PR](https://github.com/myitcv/neovim/pull/22) which should hopefully help kick-start things again. The [wiki](https://github.com/myitcv/neovim/wiki/TODO) gives an idea of the remaining work on the core `neovim` Go package, but in the meantime I'm going to update this project to work.

**Comment by myitcv** [comment]
@norcalli just pushed some updates. Please see the README [here](https://github.com/myitcv/neogo) and let me know of any problems
